name: CI
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 17.x
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Install dependencies
        run: yarn
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Build app
        run: yarn build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'